#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: head/zh_TW.UTF-8/books/handbook/disks/Makefile 39631 2012-10-01 09:53:01Z gabor $
# Original revision: 1.1
#

CHAPTERS= 	disks/chapter.xml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
